### ISSUE TITLE
保存音频后软件会闪退（或是自动关闭？）

### ISSUE THREAD

**Issue by yb** [johnsmith2077/edge-tts-gui#1]
不确定是 bug 闪退，还是 feature 自动关闭，
但编辑了半天的文本都没了，用户体验上感觉不太合理

**Comment by johnsmith2077** [comment]
正常应该是不会自动关闭的，默认会自动打开存放文件夹位置，能够稳定复现吗？我这边暂时没有出现过这个bug

**Comment by yb** [comment]
@johnsmith2077 试了一下最新版，没问题，不闪退了
